### PR TITLE
Github pages patch 1

### PR DESCRIPTION
**Pull request by zen0bit**
Little tweak for github and github pages (markdown)

If you find anything usefull, get it..

And thanks for nice project

:heart: easybashgui

### CODE REVIEW

**Comment by zen0bit** [comment]
If you wonder what i changed,
you can take a look here:
https://easybashgui.osowoso.xyz

**Comment by mckaygerhard** [comment]
nice for the web page but README is pretty unrendered in github , why not just geneated using raito ? too much dependency (gives error on yaml) and it needs of deploy

image

**Comment by zen0bit** [comment]
> nice for the web page but README is pretty unrendered/notunderstandable in github , why not just geneated using raito ? too much dependency (gives error on yaml) and it needs of deploy
> 
> image

Never heard about raito..
👍
 
This PR is really old and not updated..

**Comment by vaisarger** [comment]
Hi @zen0bit ! Thanks for your support!

I really don't know why Github didn't alert me about this issues, pull request, etc., I'm terribly sorry.
I will take a look at your comments and changes, I want that my project be a really open source and collaborative project, so thank you.

I will update this thread asap ;)

**Comment by zen0bit** [comment]
new [link](https://osowoso.github.io/easybashgui/)

**Comment by mckaygerhard** [comment]
Its nive but this depends ofn yekil and github! so if the project tries to move will need to hurry tomade a new webpage.. 

The readme is not eye candy in github only for the yekil web deploy of github, i am not agasins merged this but.. as i know this web page just provide css and no more respect the original author's at google web pages..  so i thinks **is better leave me to reorganize the readme with sections and later you @zen0bit  can modify with yekil theme..** : i mean look at those:

1 - ok you use a header tag to make an advertise? (Also readme look horrible at github render)

image

2- the changelog are embebed as headers of level 2 and are too technicals:

image

3- the library funtions only listed does not give important info

image

**Comment by zen0bit** [comment]
Updated just because link was down.

As I said also elsewhere it's old PR

You can closed if you want

As both know better solutions are already there...

So awaiting new redesign..

And thanks again for mention raito
investigating...

**Comment by zen0bit** [comment]
And that gui I don't touched in years  don't remember state but not done yet for sure

**Comment by vaisarger** [comment]
Hi @zen0bit !

Merged PR by @mckaygerhard , we look forward to your opinions and suggestions.
Moreover, there are thanks for you too in README ! ;)

**Comment by zen0bit** [comment]
I am honored

**Comment by mckaygerhard** [comment]
> I am honored

yes you are into credits at the botton of the README! @zen0bit  i bypass myselft becouse other must honored me!

**Pull request closed without merging**
