### PR TITLE
another action for releases

### PR DESCRIPTION
**Pull request by zen0bit**
This looks better for your use case...

pushed with
`git tag 0.17.0 -m "testing auto releases" && git push gh 0.17.0`

or you can use:
`git tag 0.17.0 -m "testing auto releases" && git push origin 0.17.0`
`git tag 0.17.1 -m "testing auto releases" && git push origin 0.17.1`
`git tag 1.03.0 -m "testing auto releases" && git push origin 1.03.0`

tag with three digits with dots between, will trigger release with given release number

### CODE REVIEW

**Comment by zen0bit** [comment]
respective
`git tag 12.0.7 -m "12.0.7: gum backend (frontend) added" && git push master 12.0.7`
:fireworks:

**Comment by mckaygerhard** [comment]
LGTM! :+1:  i guess this is what you wants @vaisarger  ?! right?

**Comment by vaisarger** [comment]
Looks good to me also ! 

Thank you, guys... for your good work and patience :)

**Comment by mckaygerhard** [comment]
YEAH! now next steps is projects under the BASHGUI namespace ! you two guys will see soon :face_with_spiral_eyes:

**Comment by mckaygerhard** [comment]
@zen0bit  this works so great XD

image

**Comment by zen0bit** [comment]
> @zen0bit  this works so great XD
> 
> image
> 

I am just found it.
Thanks belongs to original author...

**Pull request merged**
